-- ======================================================
-- Tipo Objetivo
insert into TTipoObjetivo (NombreTipo,Eliminado) values('WILL: ASPECTOS CONDUCTUALES',0)
insert into TTipoObjetivo (NombreTipo,Eliminado) values('SKILL: ASPECTOS TÉCNICOS ',0)

-- ======================================================
-- Tipo Onboarding

insert into TTipoOnBoarding (NombreOnBoarding,Eliminado) values('Plantilla',0)
insert into TTipoOnBoarding (NombreOnBoarding,Eliminado) values('Plan',0)
-- ======================================================
-- Objetivo
insert into TObjetivo (NombreObjetivo,IdTipoObjetivo,Eliminado) values('OBJETIVOS DE APRENDIZAJE',2,0)
insert into TObjetivo (NombreObjetivo,IdTipoObjetivo,Eliminado) values('DESARROLLO DE COMPETENCIAS',2,0)
insert into TObjetivo (NombreObjetivo,IdTipoObjetivo,Eliminado) values('OBJETIVOS DE DESEMPEÑO',2,0)
insert into TObjetivo (NombreObjetivo,IdTipoObjetivo,Eliminado) values('RESPONSABILIDAD',2,0)
insert into TObjetivo (NombreObjetivo,IdTipoObjetivo,Eliminado) values('COMPROMISO',1,0)
insert into TObjetivo (NombreObjetivo,IdTipoObjetivo,Eliminado) values('TRABAJO EN EQUIPO',1,0)
insert into TObjetivo (NombreObjetivo,IdTipoObjetivo,Eliminado) values('INTEGRIDAD',1,0)
insert into TObjetivo (NombreObjetivo,IdTipoObjetivo,Eliminado) values('SUPERACIÓN',1,0)
insert into TObjetivo (NombreObjetivo,IdTipoObjetivo,Eliminado) values('RESPETO',1,0)
insert into TObjetivo (NombreObjetivo,IdTipoObjetivo,Eliminado) values('LIDERAZGO/INFLUENCIA',1,0)

-- ==========================================================
-- Actividad
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Conocimiento del Negocio y Estructuras Organizacionales',1,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Conocimiento de la Cultura ILU / Valores organizacionales y Código de Ética',1,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Procesos de la Gerencia Financiera y procesos de Costos y Presupuestos.',1,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Conocimiento y adecuado manejo de las diferentes plataformas electrónicas que existen en la compañía.
1. SAP
2. Webdoc
3. Execution
4. Acciones de mejora 
5. APP ILU
6. SAS',1,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Modelo de Costos en SAS',1,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values(' Políticas presupuestaría y premisaspara la elaboración de presupuestos.',1,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Definición de políticas y seguimient de presupuesto de Operación de la siguiente Zafra 2022-2023',2,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Seguimiento a la ejecución presupuestaria de las unidades de la Compañía.',2,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Ejecución acumulada a la fecha y proyección de cierre de Presupuesto del periodo 2021-2022',2,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Implementación de modelos de costos y su seguimiento para determinar los costos de la empresa y de cada unidad.',2,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Margen Operativo (Ponderación)',3,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Costo Total (US$ t d azúcar) (Ponderación)',3,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Solvencia Financiera (rentabilidad + eficiencia ) (Ponderación)',3,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Cumplimiento de las Acciones de Mejora.',3,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('índice de variación de la proyección GNF del periodo.',3,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Cumplimiento del Plan de formación establecido en la plataforma ILU-Cornestone.',3,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Cumplimiento Planes de Clima Laboral en toda la organización por medio de asegurar la ejecución del programa "Minuto de Confianza".',3,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Cumplimiento de Proyectos de Innovación Costos y Presupuestos.',3,0)
insert into TActividad (NombreActividad,IdObjetivo,Eliminado) values('Evacuación de observaciones de auditoria con relación a Costos y Presupuestos.',3,0)


insert into TActividad (NombreActividad,Peso, IdObjetivo,Eliminado) values('Cumple con su deber y responde a lo acordado.',15,4,0)
insert into TActividad (NombreActividad,Peso, IdObjetivo,Eliminado) values('Es más que laborioso y va más allá de sus tareas para trascender.',10,5,0)
insert into TActividad (NombreActividad,Peso, IdObjetivo,Eliminado) values('Demuestra la unión de voluntades y el conocimiento compartido genera mejores soluciones.                                                                                                                             ',10,6,0)
insert into TActividad (NombreActividad,Peso, IdObjetivo,Eliminado) values('Demuestra transparencia, rectitud y congruencia en su actuar en cualquier situación.',20,7,0)
insert into TActividad (NombreActividad,Peso, IdObjetivo,Eliminado) values('Promueve la mejora continua y el aprendizaje constante como empresa y como personas.',10,8,0)
insert into TActividad (NombreActividad,Peso, IdObjetivo,Eliminado) values('Demuestra creencia en la dignidad de la persona y en su capacidad de desarrollo.',15,9,0)
insert into TActividad (NombreActividad,Peso, IdObjetivo,Eliminado) values('Demuestra influencia de acción positiva y genera resultados, sobre sus colaboradores (cuando aplica), compañeros y clientes.',20,10,0)

-- ==========================================================
-- Recurso
insert into TRecurso (NombreRecurso,Eliminado) values('Contrato de trabajo',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Tarjeta de seguro de vida y gastos médicos',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Formulario de Auxilio Póstumo',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Asignación de Computadora',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Usuario de internet ',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Usuario de mail',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Usuario de SAP',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Usuario de sistema propio de su área',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Usuario de Webdoc',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Usuario de Execution',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Usuario de Acciones de Mejora',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Asignación de Teléfono',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Asignación de Uniformes',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Carnet IRTRA',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Carnet de la Empresa',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Carnet de Vacunación COVID el que entrega ILU',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Asignación de Vehiculo',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Política de Préstamo',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Política de Estudios',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Hoja de Asociacion Solidarita',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Hoja de Contactos internos',0)
insert into TRecurso (NombreRecurso,Eliminado) values('Usuario APP ILU',0)
insert into TRecurso (NombreRecurso,Eliminado) values('EPP',0)


insert into TArea (NombreArea,Eliminado) values('Compensaciones y Beneficios',0)
insert into TArea (NombreArea,Eliminado) values('Tecnología de la Información',0)
insert into TArea (NombreArea,Eliminado) values('Aseguramiento de la Calidad',0)
insert into TArea (NombreArea,Eliminado) values('Gestión de Talento',0)

insert into TPuesto (NombrePuesto,IdArea,Eliminado) values('Gestor de Proyectos',1,0)
insert into TPuesto (NombrePuesto,IdArea,Eliminado) values('Gestor de Proyectos',2,0)
insert into TPuesto (NombrePuesto,IdArea,Eliminado) values('Gestor de Proyectos',3,0)
insert into TPuesto (NombrePuesto,IdArea,Eliminado) values('Gestor de Proyectos',4,0)
insert into TPuesto (NombrePuesto,IdArea,Eliminado) values('Gestor de Servicio',1,0)
insert into TPuesto (NombrePuesto,IdArea,Eliminado) values('Gestor de Servicio',2,0)
insert into TPuesto (NombrePuesto,IdArea,Eliminado) values('Gestor de Servicio',3,0)
insert into TPuesto (NombrePuesto,IdArea,Eliminado) values('Gestor de Servicio',4,0)
insert into TPuesto (NombrePuesto,IdArea,Eliminado) values('Coordinador',1,0)
insert into TPuesto (NombrePuesto,IdArea,Eliminado) values('Coordinador',2,0)
insert into TPuesto (NombrePuesto,IdArea,Eliminado) values('Coordinador',3,0)
insert into TPuesto (NombrePuesto,IdArea,Eliminado) values('Coordinador',4,0)


insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('María Regina Nájera Rodríguez','4869278829583','44835',0)

insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,1,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,2,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,3,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,4,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,5,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,6,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,7,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,8,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,9,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,10,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,11,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,12,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,13,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,14,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,15,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,16,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,17,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,18,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,19,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,20,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,21,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,22,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,23,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,1,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,2,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,3,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,4,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,5,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,6,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,7,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,8,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,9,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,10,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,11,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,12,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,13,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,14,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,15,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,16,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,17,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,18,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,19,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,20,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,21,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,22,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,23,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,1,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,2,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,3,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,4,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,5,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,6,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,7,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,8,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,9,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,10,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,11,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,12,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,13,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,14,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,15,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,16,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,17,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,18,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,19,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,20,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,21,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,22,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,23,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,1,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,2,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,3,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,4,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,5,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,6,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,7,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,8,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,9,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,10,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,11,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,12,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,13,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,14,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,15,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,16,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,17,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,18,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,19,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,20,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,21,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,22,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,23,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,1,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,2,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,3,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,4,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,5,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,6,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,7,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,8,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,9,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,10,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,11,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,12,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,13,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,14,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,15,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,16,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,17,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,18,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,19,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,20,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,21,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,22,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,23,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,1,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,2,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,3,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,4,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,5,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,6,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,7,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,8,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,9,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,10,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,11,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,12,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,13,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,14,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,15,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,16,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,17,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,18,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,19,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,20,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,21,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,22,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,23,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,1,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,2,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,3,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,4,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,5,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,6,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,7,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,8,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,9,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,10,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,11,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,12,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,13,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,14,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,15,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,16,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,17,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,18,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,19,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,20,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,21,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,22,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,23,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,1,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,2,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,3,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,4,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,5,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,6,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,7,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,8,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,9,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,10,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,11,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,12,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,13,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,14,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,15,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,16,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,17,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,18,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,19,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,20,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,21,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,22,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,23,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,1,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,2,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,3,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,4,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,5,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,6,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,7,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,8,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,9,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,10,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,11,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,12,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,13,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,14,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,15,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,16,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,17,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,18,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,19,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,20,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,21,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,22,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,23,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,1,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,2,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,3,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,4,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,5,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,6,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,7,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,8,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,9,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,10,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,11,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,12,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,13,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,14,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,15,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,16,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,17,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,18,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,19,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,20,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,21,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,22,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,23,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,1,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,2,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,3,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,4,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,5,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,6,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,7,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,8,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,9,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,10,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,11,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,12,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,13,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,14,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,15,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,16,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,17,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,18,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,19,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,20,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,21,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,22,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,23,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,1,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,2,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,3,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,4,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,5,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,6,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,7,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,8,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,9,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,10,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,11,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,12,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,13,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,14,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,15,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,16,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,17,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,18,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,19,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,20,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,21,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,22,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdPuesto,Eliminado) values(1,23,12,0)

insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('María Regina Nájera Rodríguez','4558628966618','2022-10-01','2022-10-01',1,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Carlos Estuardo Barahona Castellanos','5709282199102','2022-10-08','2022-10-08',2,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Luis Roberto Aragon Jimenez','7106447219959','2022-10-15','2022-10-15',3,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Lucas Ambrosio Shirdi Sadhu','2651151151691','2022-10-22','2022-10-22',4,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Jennifer Vanessa Santos Carrillo','9355069810464','2022-10-29','2022-10-29',5,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Keilyn Licely Lopez Gomez','3383223905850','2022-11-05','2022-11-05',6,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Josseline Paiz Carrera','7757063464882','2022-11-12','2022-11-12',7,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Admin Anghelo Hernandez','1375185324511','2022-11-19','2022-11-19',8,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Fredy Rufino Ochoa Victorio','3041675782657','2022-11-26','2022-11-26',9,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Guilder Rocael Fuentes Miranda','4532650294288','2022-12-03','2022-12-03',10,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Carlos Armando Vásquez Juan','7861597019298','2022-12-10','2022-12-10',11,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Fredy Rufino Ochoa Victorio','1772380581179','2022-12-17','2022-12-17',12,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Carlos Enrique Sazo','8665498713056','2022-12-24','2022-12-24',1,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Jonathan René Villavicencio Soto','8420368538085','2022-12-31','2022-12-31',2,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Marco Tulio Alegría López','4567393199407','2023-01-07','2023-01-07',3,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Roberto Alfredo Serrano Henriquez','9106747375698','2023-01-14','2023-01-14',4,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Jose Andres Melendez Barrios','9537752161773','2023-01-21','2023-01-21',5,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Edras Daniel Asetún García','5893522703420','2023-01-28','2023-01-28',6,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Ana Gabriela Leiva Aguilar','8125956611131','2023-02-04','2023-02-04',7,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Miguel David Ordoñez Padilla','7569996342130','2023-02-11','2023-02-11',8,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Ligia Karina Bonilla Chaves','3373059144802','2023-02-18','2023-02-18',9,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Jenner Augusto de Leon Sapon','7705668666719','2023-02-25','2023-02-25',10,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Erika Sofia Caballero Madrid','8688108079871','2023-03-04','2023-03-04',11,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Vivian Alejandra Reyes Ovalle','8653699753208','2023-03-11','2023-03-11',12,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Nelson Ivann Molina Barrios','3089592180812','2023-03-18','2023-03-18',1,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Irwing Ivan Soto Méndez','8455075254557','2023-03-25','2023-03-25',2,0)
insert into TColaborador (NombreColaborador,DPIColaborador,FechaIngreso,FechaAlta,IdPuesto,Eliminado) values('Sergio Iván Vivar','2612407160084','2023-04-01','2023-04-01',3,0)


insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,1,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,2,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,3,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,4,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,5,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,6,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,7,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,8,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,9,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,10,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,11,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,12,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,13,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,14,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,15,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,16,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,17,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,18,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,19,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,20,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,21,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,22,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,23,1,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,1,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,2,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,3,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,4,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,5,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,6,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,7,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,8,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,9,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,10,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,11,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,12,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,13,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,14,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,15,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,16,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,17,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,18,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,19,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,20,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,21,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,22,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,23,2,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,1,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,2,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,3,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,4,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,5,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,6,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,7,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,8,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,9,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,10,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,11,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,12,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,13,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,14,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,15,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,16,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,17,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,18,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,19,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,20,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,21,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,22,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,23,3,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,1,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,2,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,3,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,4,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,5,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,6,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,7,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,8,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,9,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,10,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,11,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,12,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,13,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,14,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,15,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,16,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,17,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,18,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,19,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,20,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,21,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,22,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,23,4,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,1,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,2,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,3,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,4,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,5,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,6,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,7,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,8,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,9,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,10,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,11,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,12,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,13,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,14,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,15,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,16,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,17,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,18,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,19,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,20,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,21,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,22,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,23,5,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,1,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,2,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,3,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,4,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,5,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,6,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,7,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,8,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,9,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,10,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,11,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,12,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,13,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,14,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,15,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,16,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,17,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,18,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,19,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,20,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,21,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,22,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,23,6,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,1,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,2,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,3,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,4,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,5,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,6,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,7,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,8,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,9,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,10,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,11,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,12,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,13,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,14,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,15,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,16,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,17,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,18,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,19,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,20,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,21,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,22,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,23,7,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,1,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,2,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,3,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,4,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,5,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,6,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,7,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,8,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,9,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,10,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,11,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,12,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,13,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,14,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,15,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,16,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,17,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,18,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,19,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,20,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,21,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,22,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,23,8,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,1,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,2,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,3,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,4,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,5,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,6,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,7,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,8,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,9,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,10,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,11,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,12,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,13,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,14,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,15,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,16,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,17,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,18,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,19,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,20,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,21,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,22,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,23,9,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,1,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,2,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,3,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,4,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,5,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,6,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,7,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,8,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,9,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,10,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,11,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,12,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,13,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,14,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,15,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,16,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,17,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,18,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,19,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,20,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,21,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,22,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,23,10,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,1,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,2,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,3,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,4,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,5,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,6,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,7,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,8,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,9,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,10,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,11,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,12,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,13,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,14,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,15,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,16,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,17,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,18,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,19,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,20,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,21,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,22,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,23,11,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,1,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,2,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,3,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,4,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,5,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,6,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,7,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,8,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,9,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,10,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,11,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,12,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,13,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,14,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,15,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,16,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,17,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,18,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,19,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,20,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,21,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,22,12,0)
insert into TAsignacion (TipoAsignacion,IdRecurso,IdColaborador,Eliminado) values(0,23,12,0)


insert into TPlanOnBoarding (NombreTipo,IdColaborador,FechaEvaluacion,FechaVencimiento,Realizado,NumeroEvaluacion,Eliminado) values('Plan',1,'2023-06-07','2023-06-07',1,1,0)
insert into TPlanOnBoarding (NombreTipo,IdColaborador,FechaEvaluacion,FechaVencimiento,Realizado,NumeroEvaluacion,Eliminado) values('Plan',2,'2023-06-07','2023-02-01',1,1,0)
insert into TPlanOnBoarding (NombreTipo,IdColaborador,FechaEvaluacion,FechaVencimiento,Realizado,NumeroEvaluacion,Eliminado) values('Plan',3,'2023-06-07','2023-02-01',0,1,0)

insert into TPlanOnBoarding (NombreTipo,IdColaborador,FechaEvaluacion,FechaVencimiento,Realizado,NumeroEvaluacion,Eliminado) values('Plan',10,'2023-06-08','2023-02-01',1,1,0)
insert into TPlanOnBoarding (NombreTipo,IdColaborador,FechaEvaluacion,FechaVencimiento,Realizado,NumeroEvaluacion,Eliminado) values('Plan',11,'2023-06-08','2023-02-01',1,1,0)
insert into TPlanOnBoarding (NombreTipo,IdColaborador,FechaEvaluacion,FechaVencimiento,Realizado,NumeroEvaluacion,Eliminado) values('Plan',12,'2023-06-08','2023-02-01',1,1,0)
insert into TPlanOnBoarding (NombreTipo,IdColaborador,FechaEvaluacion,FechaVencimiento,Realizado,NumeroEvaluacion,Eliminado) values('Plan',13,'2023-06-08','2023-02-01',1,1,0)
insert into TPlanOnBoarding (NombreTipo,IdColaborador,FechaEvaluacion,FechaVencimiento,Realizado,NumeroEvaluacion,Eliminado) values('Plan',14,'2023-06-08','2023-02-01',1,1,0)
insert into TPlanOnBoarding (NombreTipo,IdColaborador,FechaEvaluacion,FechaVencimiento,Realizado,NumeroEvaluacion,Eliminado) values('Plan',15,'2023-06-08','2023-02-01',1,1,0)


insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(1,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(2,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(3,1,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(4,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(5,1,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(6,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(7,1,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(8,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(9,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(10,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(11,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(12,1,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(13,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(14,1,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(15,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(16,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(17,1,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(18,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(19,1,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(20,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(21,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(22,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(23,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(24,1,50,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(25,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(26,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(27,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(28,1,50,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(29,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(30,1,50,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(31,1,50,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(32,1,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(33,1,50,0)


insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(1,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(2,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(3,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(4,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(5,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(6,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(7,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(8,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(9,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(10,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(11,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(12,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(13,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(14,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(15,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(16,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(17,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(18,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(19,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(20,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(21,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(27,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(28,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(29,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(30,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(31,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(32,2,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(33,2,100,0)

insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(1,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(2,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(3,3,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(4,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(5,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(6,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(7,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(8,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(9,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(10,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(11,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(12,3,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(13,3,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(14,3,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(15,3,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(16,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(17,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(18,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(19,3,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(20,3,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(21,3,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(27,3,50,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(28,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(29,3,50,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(30,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(31,3,50,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(32,3,0,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(33,3,50,0)


insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(1,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(2,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(3,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(4,4,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(5,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(6,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(7,4,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(8,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(9,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(10,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(11,4,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(12,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(13,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(14,4,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(15,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(16,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(17,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(18,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(19,4,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(20,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(21,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(27,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(28,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(29,4,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(30,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(31,4,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(32,4,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(33,4,100,0)


insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(1,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(2,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(3,5,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(4,5,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(5,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(6,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(7,5,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(8,5,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(9,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(10,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(11,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(12,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(13,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(14,5,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(15,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(16,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(17,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(18,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(19,5,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(20,5,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(21,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(27,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(28,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(29,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(30,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(31,5,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(32,5,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(33,5,100,0)



insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(1,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(2,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(3,6,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(4,6,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(5,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(6,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(7,6,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(8,6,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(9,6,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(10,6,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(11,6,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(12,6,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(13,6,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(14,6,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(15,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(16,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(17,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(18,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(19,6,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(20,6,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(21,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(27,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(28,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(29,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(30,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(31,6,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(32,6,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(33,6,100,0)

insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(1,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(2,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(3,7,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(4,7,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(5,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(6,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(7,7,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(8,7,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(9,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(10,7,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(11,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(12,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(13,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(14,7,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(15,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(16,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(17,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(18,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(19,7,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(20,7,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(21,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(27,7,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(28,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(29,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(30,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(31,7,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(32,7,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(33,7,100,0)

insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(1,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(2,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(3,8,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(4,8,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(5,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(6,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(7,8,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(8,8,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(9,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(10,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(11,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(12,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(13,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(14,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(15,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(16,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(17,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(18,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(19,8,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(20,8,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(21,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(27,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(28,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(29,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(30,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(31,8,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(32,8,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(33,8,100,0)

insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(1,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(2,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(3,9,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(4,9,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(5,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(6,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(7,9,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(8,9,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(9,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(10,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(11,9,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(12,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(13,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(14,9,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(15,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(16,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(17,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(18,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(19,9,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(20,9,70,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(21,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(27,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(28,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(29,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(30,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(31,9,100,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(32,9,35,0)
insert into TDetalleEvaluacion (IdActividad,IdPlanOnBoarding,Nota,Eliminado) values(33,9,100,0)

