grant select on dbo.TActividad to adminOnboarding
grant select on dbo.TArea to adminOnboarding
grant select on dbo.TAsignacion to adminOnboarding
grant select on dbo.TColaborador to adminOnboarding
grant select on dbo.TDetalleEvaluacion to adminOnboarding
grant select on dbo.TObjetivo to adminOnboarding
grant select on dbo.TPlanOnBoarding to adminOnboarding
grant select on dbo.TPuesto to adminOnboarding
grant select on dbo.TRecurso to adminOnboarding
grant select on dbo.TTipoObjetivo to adminOnboarding


grant insert on dbo.TActividad to adminOnboarding
grant insert on dbo.TArea to adminOnboarding
grant insert on dbo.TAsignacion to adminOnboarding
grant insert on dbo.TColaborador to adminOnboarding
grant insert on dbo.TDetalleEvaluacion to adminOnboarding
grant insert on dbo.TObjetivo to adminOnboarding
grant insert on dbo.TPlanOnBoarding to adminOnboarding
grant insert on dbo.TPuesto to adminOnboarding
grant insert on dbo.TRecurso to adminOnboarding
grant insert on dbo.TTipoObjetivo to adminOnboarding
grant INSERT on dbo.VCuadranteEmpleado to adminOnboarding
grant INSERT on dbo.VEscalasEmpleadoPlanOB to adminOnboarding
grant INSERT on dbo.VResultadoColaboradorSkill to adminOnboarding
grant INSERT on dbo.VResultadoColaboradorWill to adminOnboarding

grant update on dbo.TActividad to adminOnboarding
grant update on dbo.TArea to adminOnboarding
grant update on dbo.TAsignacion to adminOnboarding
grant update on dbo.TColaborador to adminOnboarding
grant update on dbo.TDetalleEvaluacion to adminOnboarding
grant update on dbo.TObjetivo to adminOnboarding
grant update on dbo.TPlanOnBoarding to adminOnboarding
grant update on dbo.TPuesto to adminOnboarding
grant update on dbo.TRecurso to adminOnboarding
grant update on dbo.TTipoObjetivo to adminOnboarding
grant update on dbo.VCuadranteEmpleado to adminOnboarding
grant update on dbo.VEscalasEmpleadoPlanOB to adminOnboarding
grant update on dbo.VResultadoColaboradorSkill to adminOnboarding
grant update on dbo.VResultadoColaboradorWill to adminOnboarding